spring:
  application:
    name: auth-app-backend
  profiles:
    active: dev


server:
  port: 8082


#configurations
#database configurations

#mysql configurations



#email configurations

#oauth2 configurations